### ISSUE TITLE
Check QGIS/ArcGIS algorithms

### ISSUE THREAD

**Issue by martinfleis** [uscuni/simplification#10] opened 2024-02-05 15:57 UTC
https://pro.arcgis.com/en/pro-app/latest/tool-reference/cartography/collapse-road-detail.htm 
https://pro.arcgis.com/en/pro-app/latest/tool-reference/cartography/merge-divided-roads.htm
https://desktop.arcgis.com/en/arcmap/latest/tools/cartography-toolbox/how-simplify-line-works.htm

**Comment by anastassiavybornova** [comment] 2024-02-05 17:11
@martinfleis the idea is that your studets will help us with this one now? :) the arcgis tool i had in mind is linked above, but i'm sure there are more... (also in qgis potentially) if i find any will link them here

**Comment by martinfleis** [comment] 2024-02-05 17:25
Yeah. Especially with Arc.

**Comment by Kryndlea** [comment] 2024-02-15 12:19
The function "Merge divided roads" in ArcGIS works does not work well for our purposes. There is a global parameter "merge distance" where you need to specify a minimum distance apart for the two lines that you want to merge. After some research of the city network I chose the distance to be 12 meters. 

While it works well in some cases, it performs poorly in others. The issue is the global setting of the distance, which also requires some knowledge of the city network.
1) If the roads/streets in the city centres or residential areas are too close, they get merged as well.
![problem1](https://github.com/uscuni/simplification/assets/131773776/82cf3dcb-0920-471f-aa8e-1381f2aab6e3)
2) And if the roads are too far apart (highways) they do not get merged.
![problem2](https://github.com/uscuni/simplification/assets/131773776/31636765-dbb9-4079-967d-0600a675edd5)
3)  In this case, the roads got merged, but the blue one in upper right corner got shifted, which also happened in the previous case.
![good_example](https://github.com/uscuni/simplification/assets/131773776/911e53c9-14d7-484c-a3f2-8b955e3b819d)

**Comment by Kryndlea** [comment] 2024-02-15 13:48
The "Collapse road detail" function will only make major changes to the network if the "merge divided roads" function has already been applied to the data. It also requires parameter for the collapse distance, which requieres some knowledge of the city network  as well. 

This image represents the data after the implementation of the "merge divided roads" function.  
![image](https://github.com/uscuni/simplification/assets/131773776/9cc7d1c7-45d6-4e83-8c70-d2d68613e1a5)

This image represents the output of the "collapse road detail" function with a set distance of 50 meters .
![image](https://github.com/uscuni/simplification/assets/131773776/45335d50-ac16-4086-8097-678d664af79a)

It works well with roundabout entrances and with smaller roundabouts, but it fails to deal with the bigger ones. If the distance is changed to 100 meters it fails to collapse some larger objects as well but it also collapses smaller blocks of streets, which i believe is not what we want.
![image](https://github.com/uscuni/simplification/assets/131773776/4a80b6a5-c39b-4fc8-966b-f64a476f5de9)

So once again, it is dependant on the global distance parameter.

I know it's not as clear from these screenshots, but wehn you overlay the layers in ArcGIS, it's easier to compare.

**Comment by dancejod** [comment] 2024-02-15 14:14
There doesn't seem to be a function for collapsing linear features in standalone QGIS. I checked out several plugins, but they mostly don't have what we want, most of them (e.g. _Geometric Attributes_, _HCMGIS_, _Geo Simplification_) are only able to construct chordal axes of polygons. There is this plugin _Cartography tools_ that actually has functions _Collapse dual carriageways_ and _Remove turnabouts_, but I haven't managed to get them to work (the author had stated that it's still WIP).

Not QGIS, but there exists this [Skeletron](https://github.com/migurski/Skeletron) tool that could be useful.

**Comment by martinfleis** [comment] 2024-02-15 15:41
@dancejod do you have a link to the Cartography tools plugin?

**Comment by jGaboardi** [comment] 2024-07-24 13:26
@martinfleis Is this still *In Progress* or is it *Done*?

**Comment by martinfleis** [comment] 2024-07-24 13:52
No clue

**Comment by Kryndlea** [comment] 2024-07-25 08:48
Done for my part (explore function in arcgis)

**Closed** 2024-07-25 11:49 UTC
Labels: algo/method, eval
